server:
  port: 8080

spring:
  # application
  application:
    name: support-svc
  # datasource
#  datasource:
#    url: jdbc:h2:mem:test
#    username: admin
#    password: admin
#    driver-class-name: org.h2.Driver
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      maximum-pool-size: 100
#      minimum-idle: 1
#      idle-timeout: 30000
#      max-lifetime: 180000
#      connection-timeout: 300000
#      auto-commit: false
#      pool-name: H2-Pool
#  # h2 console
#  h2:
#    console:
#      enabled: true
#      path: /h2/console
#  # jpa
#  jpa:
#    hibernate:
#        ddl-auto: create
#
## cache
#cache:
#  caffeine:
#    maximum-size: 100
#    expireAfterWrite: 60
#
## meowu
#meowu:
#  web:
#    cors:
#      enabled: true
#    request-log:
#      enabled: true
#    converter: gson